#[=======================================================================[.rst:
DoxygenTarget
-------------

Adds an optional ``docs`` build target that runs Doxygen and Sphinx to
produce HTML documentation.

The pipeline is:

1. Doxygen reads ``include/`` and ``src/``, writes XML to
   ``<build>/doxygen/xml/``.  HTML output is disabled — Sphinx handles
   rendering.
2. Sphinx reads ``docs/`` RST sources and the Doxygen XML via Breathe.
   CMake bracket comments in ``cmake/`` are rendered by the
   ``sphinxcontrib.moderncmakedomain`` extension (same one the CMake
   project uses for its own documentation).
3. Furo theme produces the final HTML site in ``<build>/sphinx/html/``.

.. note::
   The ``docs`` target is off by default so CI and regular builds are
   not slowed down by doc generation.  Enable with ``-DBUILD_DOCS=ON``.

.. code-block:: bash

   # One-time Python setup (run from the repo root)
   pip install -r docs/requirements-docs.txt

   # Configure and build
   cmake -B build -DBUILD_DOCS=ON
   cmake --build build --target docs

   # Open the result
   open build/sphinx/html/index.html   # macOS
   xdg-open build/sphinx/html/index.html  # Linux

CMake options
^^^^^^^^^^^^^

``BUILD_DOCS``
   Set to ``ON`` to enable the ``docs`` target.  Default: ``OFF``.

   .. code-block:: bash

      cmake -DBUILD_DOCS=ON ..

#]=======================================================================]

include_guard(GLOBAL)

option(BUILD_DOCS "Build API and narrative documentation (Doxygen + Sphinx)" OFF)

if(NOT BUILD_DOCS)
    return()
endif()

# ---------------------------------------------------------------------------
# Doxygen
# ---------------------------------------------------------------------------
find_package(Doxygen REQUIRED
    OPTIONAL_COMPONENTS dot
)
# Dot (Graphviz) is intentionally optional: we disable graph generation in
# Doxyfile.in (HAVE_DOT = NO), but find_package still tries to find it.
# OPTIONAL_COMPONENTS silences the "dot not found" warning.

# ---------------------------------------------------------------------------
# Sphinx
# Looked up via find_program rather than find_package because there is no
# official CMake FindSphinx module.  sphinx-build is always on PATH after
# `pip install sphinx`.
# ---------------------------------------------------------------------------
find_program(SPHINX_BUILD_EXECUTABLE
    NAMES sphinx-build
    DOC   "Path to the sphinx-build executable"
)
if(NOT SPHINX_BUILD_EXECUTABLE)
    message(FATAL_ERROR
        "[cppenv] sphinx-build not found. "
        "Run: pip install -r docs/requirements-docs.txt"
    )
endif()

# ---------------------------------------------------------------------------
# Paths
# All output goes under CMAKE_CURRENT_BINARY_DIR so `cmake --build . --target
# clean` removes it and the source tree stays unmodified.
# ---------------------------------------------------------------------------
set(DOXYGEN_OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/doxygen")
set(SPHINX_CONF_DIR    "${CMAKE_CURRENT_BINARY_DIR}/docs")
set(SPHINX_OUTPUT_DIR  "${CMAKE_CURRENT_BINARY_DIR}/sphinx/html")

# ---------------------------------------------------------------------------
# Configure Doxyfile and conf.py from their .in templates.
# @ONLY ensures only @VAR@ tokens are substituted; ${VAR} syntax in the
# templates (used by Python) is left untouched.
# ---------------------------------------------------------------------------
configure_file(
    "${CMAKE_CURRENT_SOURCE_DIR}/docs/Doxyfile.in"
    "${CMAKE_CURRENT_BINARY_DIR}/Doxyfile"
    @ONLY
)

configure_file(
    "${CMAKE_CURRENT_SOURCE_DIR}/docs/conf.py.in"
    "${SPHINX_CONF_DIR}/conf.py"
    @ONLY
)

# ---------------------------------------------------------------------------
# Custom target: docs
#
# Step 1: Doxygen → XML (never HTML — Sphinx owns the HTML output).
# Step 2: sphinx-build reads docs/ RST sources, the Doxygen XML via
#         Breathe, and cmake/ bracket comments via sphinx-cmake.
#
# -c <conf_dir>  tells sphinx-build where conf.py lives (in the binary dir
#                because it was generated by configure_file above).
# <source_dir>   is the docs/ directory in the source tree (RST files).
# <output_dir>   is where the HTML site lands.
#
# VERBATIM prevents CMake from quoting/escaping arguments — required for
# sphinx-build's positional argument handling.
# ---------------------------------------------------------------------------
add_custom_target(docs
    COMMAND
        ${DOXYGEN_EXECUTABLE} "${CMAKE_CURRENT_BINARY_DIR}/Doxyfile"
    COMMAND
        ${SPHINX_BUILD_EXECUTABLE}
            -b html
            -c "${SPHINX_CONF_DIR}"
            "${CMAKE_CURRENT_SOURCE_DIR}/docs"
            "${SPHINX_OUTPUT_DIR}"
    WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
    COMMENT "Building documentation: Doxygen → XML → Breathe → Sphinx + Furo"
    VERBATIM
)

message(STATUS "[cppenv] BUILD_DOCS=ON — 'docs' target enabled")
message(STATUS "[cppenv]   Output: ${SPHINX_OUTPUT_DIR}/index.html")
